### ISSUE TITLE
Clarify project state

### ISSUE THREAD

**Issue by UgnilJoZ** [Smithay/input.rs#15]
There is currently a fat warning in the readme: "This remains untested until used in https://github.com/vberger/smithay/".

But according to https://github.com/vberger/smithay/blob/master/Cargo.toml#L30 (which redirects), it is already included.

Is the notice still justified?

**Comment by Drakulix** [comment]
Yes, you are right. It is probably not (anymore) justified.

Smithay is using it for quite some time now without major issue and other projects are also using the current version.

So while I cannot say this for the whole api surface (as people still find [some oversights](d645ae1c1dcab5d322db8d74b283962f166601bd)), generally this library is definitely usable.

Thanks for bringing that up, I removed the paragraph from the README.
