### ISSUE TITLE
Anyway to "consume" an event?

### ISSUE THREAD

**Issue by emhagman** [Smithay/input.rs#21]
Hi,

Not sure if this is the right place to ask, but is there a way to "consume" an event that has been listened to? For instance, if I notice the "a" key has been pressed, could I prevent it from typing a character?

I've only found:

https://wayland.freedesktop.org/libinput/doc/latest/configuration.html#send-events-mode
https://github.com/Smithay/input.rs/blob/1afe2ee868c89c62c9920a760313609d612d0a1f/src/device.rs#L1283

But it looks like that would prevent the entire device from sending events? Same thing with `EVIOCGRAB` with `ioctl` as far as I can tell. Is there really no other way to do this besides then emulating and echoing the input received when preventing other programs from reading from the device?

Thanks!

**Comment by Drakulix** [comment]
Sorry, I totally forgot about this issue.

That is not what libinput does. libinput just gives your access to different input devices in an orderly fashion. There is no way to prevent other users of libinput (or other programs using the kernel apis directly) to receive them as well.

libinput is a very low-level library. If you want to intercept inputs you need something more high-level and support for that feature in your desktop environment.

**Comment by emhagman** [comment]
No problem, thanks for responding!
