### ISSUE TITLE
Problem with linking

### ISSUE THREAD

**Issue by Dworv** [Smithay/input.rs#39]
When running on Fedora, Xorg, libinput 1.21, I get a linking error on compile.
```
   Compiling snarvei v0.1.0 (/home/dworv/Hacking/Projects/snarvei)
error: linking with `cc` failed: exit status: 1
  |
  = note: I TOOK OUT THIS GIANT BLOCK OF PATHS
  = note: /usr/bin/ld: cannot find -linput
          collect2: error: ld returned 1 exit status
          

error: could not compile `snarvei` due to previous error
```
Is this a known issue? How can I fix it?

**Comment by Drakulix** [comment]
Have you installed libinput-devel? Because I am linking on Fedora just fine.

**Comment by Dworv** [comment]
Oh! Of course I need that. Thank you. I'll close this when I can confirm it works.

**Comment by Dworv** [comment]
It works.
