### ISSUE TITLE
Adding bindings for libei

### ISSUE THREAD

**Issue by pentamassiv** [Smithay/input.rs#50]
Thank you for creating these bindings. https://gitlab.freedesktop.org/libinput/libei is a library to emulate input. Is this out of scope of this Github org/ repo or are you considering to add bindings for it?
Thanks :)

**Comment by Drakulix** [comment]
I do absolutely consider this in scope for the `smithay`-org, but I would prefer to do the bindings as a crate separate from the libinput-bindings.

An additional api to accumulate input from different sources like [`libinput`] or [`libei`] could also be build on top of those later as another crate or as part of the [`smithay`](https://github.com/Smithay/smithay) framework.

However I have not yet spend any time on doing any of this and to be entirely honest, it is not very high on the priority list, right now (atleast not on mine).

Contributions are highly welcome however. Feel free to reach out on [matrix](https://matrix.to/#/#smithay:matrix.org), if you feel like tackling this issue! :)

**Comment by pentamassiv** [comment]
Okay, thank you very much for the fast response. I might look into it because we are reviving the [enigo](https://crates.io/crates/enigo) crate and I would like to add Wayland support for it. Unfortunately it is a bit of a mess with lots of different approaches floating around.

**Comment by Drakulix** [comment]
https://github.com/ids1024/reis
