### ISSUE TITLE
Cannot seem to be able to load `/dev/input/event0` (a HORI PAD controller)

### ISSUE THREAD

**Issue by hansl** [Smithay/input.rs#58]
I get all others devices to load proper, but `/.../event0`, even though it calls the `LibInterface` and succeeds, doesn't seem to load. It shows properly in `evtest` or if I `cat /dev/input/event0` I can see the events.

Same if I add an XBox controller (in my log below it's `/.../event12`); `LibInterface::open_restricted` is called and succeeds, but `input` doesn't poll the events correctly.

I'm still investigating and will update here if/when I found more information.

Log:

```
open_restricted: "/dev/input/event1"
....... Ok(OwnedFd { fd: 6 })
open_restricted: "/dev/input/event2"
....... Ok(OwnedFd { fd: 7 })
open_restricted: "/dev/input/event3"
....... Ok(OwnedFd { fd: 8 })
open_restricted: "/dev/input/event4"
....... Ok(OwnedFd { fd: 9 })
open_restricted: "/dev/input/event5"
....... Ok(OwnedFd { fd: 10 })
open_restricted: "/dev/input/event6"
....... Ok(OwnedFd { fd: 11 })
open_restricted: "/dev/input/event10"
....... Ok(OwnedFd { fd: 12 })
open_restricted: "/dev/input/event11"
....... Ok(OwnedFd { fd: 12 })
open_restricted: "/dev/input/event7"
....... Ok(OwnedFd { fd: 12 })
open_restricted: "/dev/input/event8"
....... Ok(OwnedFd { fd: 13 })
open_restricted: "/dev/input/event9"
....... Ok(OwnedFd { fd: 14 })
open_restricted: "/dev/input/event0"
....... Ok(OwnedFd { fd: 15 })
Added device: Added(DeviceAddedEvent @0x9f0288) "event1"
Added device: Added(DeviceAddedEvent @0x9fc638) "event2"
Added device: Added(DeviceAddedEvent @0xa05c88) "event3"
Added device: Added(DeviceAddedEvent @0xa0f610) "event4"
Added device: Added(DeviceAddedEvent @0xa18fb0) "event5"
Added device: Added(DeviceAddedEvent @0xa22788) "event6"
Added device: Added(DeviceAddedEvent @0xa2c050) "event7"
Added device: Added(DeviceAddedEvent @0xa358a0) "event8"
Added device: Added(DeviceAddedEvent @0xa3ef48) "event9"
open_restricted: "/dev/input/event12"
....... Ok(OwnedFd { fd: 15 })

```

**Comment by Drakulix** [comment]
Libinput generally doesn't handle gamepads, controllers, similar devices. It will check for evdev properties, that categorize it as absolute-pointer, tablet, relative-pointer, keyboard, etc device, but it does intentionally not pick up any device classes it doesn't recognize. And it is not built to handle game controllers.

**Comment by hansl** [comment]
Yes, I've just noticed that even the libinput test suite won't see those controllers (took me a while to build it for my target platform, sorry). I thought it was a bug because `evtest` does handle it properly, but `evtest` opens the file directly and doesn't use `libinput`.

This is not the fault of this library, so I'll close this issue.
