### ISSUE TITLE
Linking error on ubuntu 22.04 libinput_device_config_dwtp_set_enabled

### ISSUE THREAD

**Issue by ViddeM** [Smithay/input.rs#71]
When building a project depending on libinput I get a linking error saying:
`input-0.9.0/src/device.rs:995: undefined reference to `libinput_device_config_dwtp_set_enabled'` 

I saw #59 but I already had such a symlink and furthermore my error seems unrelated (but feel free to educate me if I'm wrong). 

My `libinput` version is 1.20.

**Comment by Drakulix** [comment]
You are using a rather old system, as such your system likely doesn't ship a recent enough version of libinput, that has the required function.

By default this crate always assumes the highest version: https://github.com/Smithay/input.rs/blob/master/Cargo.toml#L33

You have to disable the default features to fix this.

**Comment by ViddeM** [comment]
Ah I see, yeah I'm using a company provided variant of ubuntu and they don't support 24 yet :cry:

I got this issue trying to compile another project (not one of mine): niri (https://github.com/YaLTeR/niri) but after changing things to make it compile with the 1_19 feature it seems to be compiling now. Let's see how much I screwed up doing that x)

Thanks for the quick reply anyways! :)

**Comment by Drakulix** [comment]
If it just works niri is likely not using the method either, in that case maybe make a PR to disable the feature. Otherwise downstream in general needs to detect this during compile-time and work around missing methods.

No problem!
